

[build]
  publish = "."  # Racine du projet car vous avez index.html à la racine
  command = "echo 'Build réussi - Site statique'"

[build.environment]
  NODE_VERSION = "18"

# Configuration pour le serveur de développement
[dev]
  port = 3000
  publish = "."

# Redirections pour le SPA-like behavior (optionnel)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Redirections de sécurité
[[redirects]]
  from = "/.env"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "/wp-admin/*"
  to = "/404.html"
  status = 404

# Headers de sécurité simplifiés
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache pour les assets statiques
[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Configuration de base pour les contextes
[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"